version: '3'
services:
  api:
    build: .
    depends_on:
      - postgres
    ports: 
      - 8000:8000
    volumes:
      - ./app:/usr/src/app/app:ro #bind volume to sync changes ro = read only
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./.env
      

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Tmkoc1234
      - POSTGRES_DB=fastapi
      - POSTGRES_USER=surya

    volumes:
      - postgres-db:/var/lib/postgresql/data
    
volumes:
  postgres-db:
